//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooksClient.CustomerManagerService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://manager.ia.zut.locon.pl/")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://manager.ia.zut.locon.pl/")]
    public partial class address : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string address1Field;
        
        private string address2Field;
        
        private string cityField;
        
        private string postCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string address1 {
            get {
                return this.address1Field;
            }
            set {
                this.address1Field = value;
                this.RaisePropertyChanged("address1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
                this.RaisePropertyChanged("address2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("city");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string postCode {
            get {
                return this.postCodeField;
            }
            set {
                this.postCodeField = value;
                this.RaisePropertyChanged("postCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://manager.ia.zut.locon.pl/")]
    public partial class customer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private address billingAddressField;
        
        private string birthField;
        
        private address deliveryAddressField;
        
        private string emailField;
        
        private string firstnameField;
        
        private string lastnameField;
        
        private string phoneField;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public address billingAddress {
            get {
                return this.billingAddressField;
            }
            set {
                this.billingAddressField = value;
                this.RaisePropertyChanged("billingAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string birth {
            get {
                return this.birthField;
            }
            set {
                this.birthField = value;
                this.RaisePropertyChanged("birth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public address deliveryAddress {
            get {
                return this.deliveryAddressField;
            }
            set {
                this.deliveryAddressField = value;
                this.RaisePropertyChanged("deliveryAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string firstname {
            get {
                return this.firstnameField;
            }
            set {
                this.firstnameField = value;
                this.RaisePropertyChanged("firstname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string lastname {
            get {
                return this.lastnameField;
            }
            set {
                this.lastnameField = value;
                this.RaisePropertyChanged("lastname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
                this.RaisePropertyChanged("phone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://manager.ia.zut.locon.pl/", ConfigurationName="CustomerManagerService.CustomerManager")]
    public interface CustomerManager {
        
        // CODEGEN: Parametr „customer” wymaga dodatkowych informacji o schemacie, których nie można uzyskać w trybie parametru. Określony atrybut to „System.Xml.Serialization.XmlElementAttribute”.
        [System.ServiceModel.OperationContractAttribute(Action="http://manager.ia.zut.locon.pl/CustomerManager/getCustomerListByLastnameRequest", ReplyAction="http://manager.ia.zut.locon.pl/CustomerManager/getCustomerListByLastnameResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BooksClient.CustomerManagerService.Exception), Action="http://manager.ia.zut.locon.pl/CustomerManager/getCustomerListByLastname/Fault/Ex" +
            "ception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="customer")]
        BooksClient.CustomerManagerService.getCustomerListByLastnameResponse getCustomerListByLastname(BooksClient.CustomerManagerService.getCustomerListByLastnameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://manager.ia.zut.locon.pl/CustomerManager/getCustomerListByLastnameRequest", ReplyAction="http://manager.ia.zut.locon.pl/CustomerManager/getCustomerListByLastnameResponse")]
        System.Threading.Tasks.Task<BooksClient.CustomerManagerService.getCustomerListByLastnameResponse> getCustomerListByLastnameAsync(BooksClient.CustomerManagerService.getCustomerListByLastnameRequest request);
        
        // CODEGEN: Parametr „customer” wymaga dodatkowych informacji o schemacie, których nie można uzyskać w trybie parametru. Określony atrybut to „System.Xml.Serialization.XmlElementAttribute”.
        [System.ServiceModel.OperationContractAttribute(Action="http://manager.ia.zut.locon.pl/CustomerManager/getCustomerListByFirstnameRequest", ReplyAction="http://manager.ia.zut.locon.pl/CustomerManager/getCustomerListByFirstnameResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(BooksClient.CustomerManagerService.Exception), Action="http://manager.ia.zut.locon.pl/CustomerManager/getCustomerListByFirstname/Fault/E" +
            "xception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="customer")]
        BooksClient.CustomerManagerService.getCustomerListByFirstnameResponse getCustomerListByFirstname(BooksClient.CustomerManagerService.getCustomerListByFirstnameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://manager.ia.zut.locon.pl/CustomerManager/getCustomerListByFirstnameRequest", ReplyAction="http://manager.ia.zut.locon.pl/CustomerManager/getCustomerListByFirstnameResponse" +
            "")]
        System.Threading.Tasks.Task<BooksClient.CustomerManagerService.getCustomerListByFirstnameResponse> getCustomerListByFirstnameAsync(BooksClient.CustomerManagerService.getCustomerListByFirstnameRequest request);
        
        // CODEGEN: Parametr „sid” wymaga dodatkowych informacji o schemacie, których nie można uzyskać w trybie parametru. Określony atrybut to „System.Xml.Serialization.XmlElementAttribute”.
        [System.ServiceModel.OperationContractAttribute(Action="http://manager.ia.zut.locon.pl/CustomerManager/loginRequest", ReplyAction="http://manager.ia.zut.locon.pl/CustomerManager/loginResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BooksClient.CustomerManagerService.Exception), Action="http://manager.ia.zut.locon.pl/CustomerManager/login/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="sid")]
        BooksClient.CustomerManagerService.loginResponse login(BooksClient.CustomerManagerService.loginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://manager.ia.zut.locon.pl/CustomerManager/loginRequest", ReplyAction="http://manager.ia.zut.locon.pl/CustomerManager/loginResponse")]
        System.Threading.Tasks.Task<BooksClient.CustomerManagerService.loginResponse> loginAsync(BooksClient.CustomerManagerService.loginRequest request);
        
        // CODEGEN: Parametr „return” wymaga dodatkowych informacji o schemacie, których nie można uzyskać w trybie parametru. Określony atrybut to „System.Xml.Serialization.XmlElementAttribute”.
        [System.ServiceModel.OperationContractAttribute(Action="http://manager.ia.zut.locon.pl/CustomerManager/removeSessionRequest", ReplyAction="http://manager.ia.zut.locon.pl/CustomerManager/removeSessionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BooksClient.CustomerManagerService.Exception), Action="http://manager.ia.zut.locon.pl/CustomerManager/removeSession/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BooksClient.CustomerManagerService.removeSessionResponse removeSession(BooksClient.CustomerManagerService.removeSessionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://manager.ia.zut.locon.pl/CustomerManager/removeSessionRequest", ReplyAction="http://manager.ia.zut.locon.pl/CustomerManager/removeSessionResponse")]
        System.Threading.Tasks.Task<BooksClient.CustomerManagerService.removeSessionResponse> removeSessionAsync(BooksClient.CustomerManagerService.removeSessionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCustomerListByLastname", WrapperNamespace="http://manager.ia.zut.locon.pl/", IsWrapped=true)]
    public partial class getCustomerListByLastnameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://manager.ia.zut.locon.pl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lastname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://manager.ia.zut.locon.pl/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sid;
        
        public getCustomerListByLastnameRequest() {
        }
        
        public getCustomerListByLastnameRequest(string lastname, string sid) {
            this.lastname = lastname;
            this.sid = sid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCustomerListByLastnameResponse", WrapperNamespace="http://manager.ia.zut.locon.pl/", IsWrapped=true)]
    public partial class getCustomerListByLastnameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://manager.ia.zut.locon.pl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("customer", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BooksClient.CustomerManagerService.customer[] customer;
        
        public getCustomerListByLastnameResponse() {
        }
        
        public getCustomerListByLastnameResponse(BooksClient.CustomerManagerService.customer[] customer) {
            this.customer = customer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCustomerListByFirstname", WrapperNamespace="http://manager.ia.zut.locon.pl/", IsWrapped=true)]
    public partial class getCustomerListByFirstnameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://manager.ia.zut.locon.pl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string firstname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://manager.ia.zut.locon.pl/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sid;
        
        public getCustomerListByFirstnameRequest() {
        }
        
        public getCustomerListByFirstnameRequest(string firstname, string sid) {
            this.firstname = firstname;
            this.sid = sid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCustomerListByFirstnameResponse", WrapperNamespace="http://manager.ia.zut.locon.pl/", IsWrapped=true)]
    public partial class getCustomerListByFirstnameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://manager.ia.zut.locon.pl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("customer", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BooksClient.CustomerManagerService.customer[] customer;
        
        public getCustomerListByFirstnameResponse() {
        }
        
        public getCustomerListByFirstnameResponse(BooksClient.CustomerManagerService.customer[] customer) {
            this.customer = customer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="login", WrapperNamespace="http://manager.ia.zut.locon.pl/", IsWrapped=true)]
    public partial class loginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://manager.ia.zut.locon.pl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://manager.ia.zut.locon.pl/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        public loginRequest() {
        }
        
        public loginRequest(string user, string password) {
            this.user = user;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="loginResponse", WrapperNamespace="http://manager.ia.zut.locon.pl/", IsWrapped=true)]
    public partial class loginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://manager.ia.zut.locon.pl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sid;
        
        public loginResponse() {
        }
        
        public loginResponse(string sid) {
            this.sid = sid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeSession", WrapperNamespace="http://manager.ia.zut.locon.pl/", IsWrapped=true)]
    public partial class removeSessionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://manager.ia.zut.locon.pl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sid;
        
        public removeSessionRequest() {
        }
        
        public removeSessionRequest(string sid) {
            this.sid = sid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeSessionResponse", WrapperNamespace="http://manager.ia.zut.locon.pl/", IsWrapped=true)]
    public partial class removeSessionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://manager.ia.zut.locon.pl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public removeSessionResponse() {
        }
        
        public removeSessionResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CustomerManagerChannel : BooksClient.CustomerManagerService.CustomerManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerManagerClient : System.ServiceModel.ClientBase<BooksClient.CustomerManagerService.CustomerManager>, BooksClient.CustomerManagerService.CustomerManager {
        
        public CustomerManagerClient() {
        }
        
        public CustomerManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BooksClient.CustomerManagerService.getCustomerListByLastnameResponse BooksClient.CustomerManagerService.CustomerManager.getCustomerListByLastname(BooksClient.CustomerManagerService.getCustomerListByLastnameRequest request) {
            return base.Channel.getCustomerListByLastname(request);
        }
        
        public BooksClient.CustomerManagerService.customer[] getCustomerListByLastname(string lastname, string sid) {
            BooksClient.CustomerManagerService.getCustomerListByLastnameRequest inValue = new BooksClient.CustomerManagerService.getCustomerListByLastnameRequest();
            inValue.lastname = lastname;
            inValue.sid = sid;
            BooksClient.CustomerManagerService.getCustomerListByLastnameResponse retVal = ((BooksClient.CustomerManagerService.CustomerManager)(this)).getCustomerListByLastname(inValue);
            return retVal.customer;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BooksClient.CustomerManagerService.getCustomerListByLastnameResponse> BooksClient.CustomerManagerService.CustomerManager.getCustomerListByLastnameAsync(BooksClient.CustomerManagerService.getCustomerListByLastnameRequest request) {
            return base.Channel.getCustomerListByLastnameAsync(request);
        }
        
        public System.Threading.Tasks.Task<BooksClient.CustomerManagerService.getCustomerListByLastnameResponse> getCustomerListByLastnameAsync(string lastname, string sid) {
            BooksClient.CustomerManagerService.getCustomerListByLastnameRequest inValue = new BooksClient.CustomerManagerService.getCustomerListByLastnameRequest();
            inValue.lastname = lastname;
            inValue.sid = sid;
            return ((BooksClient.CustomerManagerService.CustomerManager)(this)).getCustomerListByLastnameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BooksClient.CustomerManagerService.getCustomerListByFirstnameResponse BooksClient.CustomerManagerService.CustomerManager.getCustomerListByFirstname(BooksClient.CustomerManagerService.getCustomerListByFirstnameRequest request) {
            return base.Channel.getCustomerListByFirstname(request);
        }
        
        public BooksClient.CustomerManagerService.customer[] getCustomerListByFirstname(string firstname, string sid) {
            BooksClient.CustomerManagerService.getCustomerListByFirstnameRequest inValue = new BooksClient.CustomerManagerService.getCustomerListByFirstnameRequest();
            inValue.firstname = firstname;
            inValue.sid = sid;
            BooksClient.CustomerManagerService.getCustomerListByFirstnameResponse retVal = ((BooksClient.CustomerManagerService.CustomerManager)(this)).getCustomerListByFirstname(inValue);
            return retVal.customer;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BooksClient.CustomerManagerService.getCustomerListByFirstnameResponse> BooksClient.CustomerManagerService.CustomerManager.getCustomerListByFirstnameAsync(BooksClient.CustomerManagerService.getCustomerListByFirstnameRequest request) {
            return base.Channel.getCustomerListByFirstnameAsync(request);
        }
        
        public System.Threading.Tasks.Task<BooksClient.CustomerManagerService.getCustomerListByFirstnameResponse> getCustomerListByFirstnameAsync(string firstname, string sid) {
            BooksClient.CustomerManagerService.getCustomerListByFirstnameRequest inValue = new BooksClient.CustomerManagerService.getCustomerListByFirstnameRequest();
            inValue.firstname = firstname;
            inValue.sid = sid;
            return ((BooksClient.CustomerManagerService.CustomerManager)(this)).getCustomerListByFirstnameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BooksClient.CustomerManagerService.loginResponse BooksClient.CustomerManagerService.CustomerManager.login(BooksClient.CustomerManagerService.loginRequest request) {
            return base.Channel.login(request);
        }
        
        public string login(string user, string password) {
            BooksClient.CustomerManagerService.loginRequest inValue = new BooksClient.CustomerManagerService.loginRequest();
            inValue.user = user;
            inValue.password = password;
            BooksClient.CustomerManagerService.loginResponse retVal = ((BooksClient.CustomerManagerService.CustomerManager)(this)).login(inValue);
            return retVal.sid;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BooksClient.CustomerManagerService.loginResponse> BooksClient.CustomerManagerService.CustomerManager.loginAsync(BooksClient.CustomerManagerService.loginRequest request) {
            return base.Channel.loginAsync(request);
        }
        
        public System.Threading.Tasks.Task<BooksClient.CustomerManagerService.loginResponse> loginAsync(string user, string password) {
            BooksClient.CustomerManagerService.loginRequest inValue = new BooksClient.CustomerManagerService.loginRequest();
            inValue.user = user;
            inValue.password = password;
            return ((BooksClient.CustomerManagerService.CustomerManager)(this)).loginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BooksClient.CustomerManagerService.removeSessionResponse BooksClient.CustomerManagerService.CustomerManager.removeSession(BooksClient.CustomerManagerService.removeSessionRequest request) {
            return base.Channel.removeSession(request);
        }
        
        public bool removeSession(string sid) {
            BooksClient.CustomerManagerService.removeSessionRequest inValue = new BooksClient.CustomerManagerService.removeSessionRequest();
            inValue.sid = sid;
            BooksClient.CustomerManagerService.removeSessionResponse retVal = ((BooksClient.CustomerManagerService.CustomerManager)(this)).removeSession(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BooksClient.CustomerManagerService.removeSessionResponse> BooksClient.CustomerManagerService.CustomerManager.removeSessionAsync(BooksClient.CustomerManagerService.removeSessionRequest request) {
            return base.Channel.removeSessionAsync(request);
        }
        
        public System.Threading.Tasks.Task<BooksClient.CustomerManagerService.removeSessionResponse> removeSessionAsync(string sid) {
            BooksClient.CustomerManagerService.removeSessionRequest inValue = new BooksClient.CustomerManagerService.removeSessionRequest();
            inValue.sid = sid;
            return ((BooksClient.CustomerManagerService.CustomerManager)(this)).removeSessionAsync(inValue);
        }
    }
}
